name: Nathan
favicon: null
layout_spectrum: 0.45173232490196824
typography_spectrum: 0.49163451278582215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5516628529876471
  lightness: 0.4558179534506053
  saturation: 0.17993305018171668
  rhythmicContrast: 0.01796491048298776
purpose: []
